WIP: Migrate annotation editor to react
grafana/opensearch-datasource pull request #36
Opened 2022-06-09 11:36 UTC by svennergr

**Change base to main once #35 is merged.**

What this PR does / why we need it:

This PR migrates the Opensearch annotation editor from angular to react.

Which issue(s) this PR fixes:

Fixes #28

2022-06-10 09:52 UTC, joey-grafana requested changes
Opening the annotation editor shows the following error:

Also, please note that the default editor appears to be displayed below the new `AnnotationQueryEditor`. We only want the editor you created as it matches the old editor :) 

![Screenshot 2022-06-10 at 10 48 13](https://user-images.githubusercontent.com/90795735/173039756-0d96d17f-2d66-4118-ab03-354cea0e0bf0.png)

2022-06-10 09:52 UTC, joey-grafana commented on src/components/QueryEditor/AnnotationQueryEditor.tsx
> +            query={annotation.target.query}
```suggestion
            query={annotation.target?.query}
```
or we might get something like this.. :D 

![Screenshot 2022-06-09 at 17 49 21](https://user-images.githubusercontent.com/90795735/173039640-2957b309-03eb-4a70-a32f-947f502573b5.png)

2022-06-10 10:29 UTC, svennergr commented
> Also, please note that the default editor appears to be displayed below the new AnnotationQueryEditor. We only want the editor you created as it matches the old editor :)

Oh yeah, I do had to change https://github.com/grafana/grafana/blob/cb96f51c733460f37d895bbcda3322b5965640bf/public/app/features/annotations/standardAnnotationSupport.ts#L237 in order for this to show as the only editor. 

I will go ahead and open a PR for this in the grafana repository. This should also resolve the errors you are getting.

2022-06-10 11:13 UTC, joey-grafana approved these changes
Looks great, good job buddy :) 

Could you open up the grafana/grafana PR in `standardAnnotationSupport.ts` before you merge this please.

2022-06-13 08:48 UTC, svennergr commented
> Could you open up the grafana/grafana PR in `standardAnnotationSupport.ts` before you merge this please.

Corresponding PR in grafana: https://github.com/grafana/grafana/pull/50655

2022-06-13 14:40 UTC, joey-grafana commented
As discussed, we won't be merging this pr until we have updated our @ Grafana 7.5.7 packages.

2022-06-15 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/opensearch-datasource?pullRequest=36) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/opensearch-datasource?pullRequest=36) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/opensearch-datasource?pullRequest=36) it.</sub>

2022-06-30 09:22 UTC, merged