Use resource handler to get version
grafana/opensearch-datasource pull request #452
Opened 2024-09-13 21:44 UTC by iwysiu

**What this PR does / why we need it**:
This pr sets up the resource handler (taken from [elasticsearch](https://github.com/grafana/grafana/blob/d1ffcc22d915ab88599c627275cdcf6203e32084/pkg/tsdb/elasticsearch/elasticsearch.go#L190)) and uses it to get the opensearch version

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2024-09-17 10:53 UTC, njvrzm requested changes
Looks good - comments are all minor - and works well when it works, but it fails in a pretty ugly way if the request to the opensearch server fails. Screenshot is what you see after "Get Version and Save" if the server isn't running, or you have the wrong auth, or there's TLS error, etc. Probably fine to just put something generic like "Failed to connect to server", at least for now.
<img width="1205" alt="Screenshot 2024-09-17 at 12 21 30" src="https://github.com/user-attachments/assets/a6c7a08a-c798-4a9e-8a64-88314e8f0fc1">

2024-09-17 10:53 UTC, njvrzm commented on pkg/opensearch/opensearch.go
> +	esUrlString := osUrl.String()
```suggestion
	osUrlString := osUrl.String()
```

2024-09-17 10:53 UTC, njvrzm commented on pkg/opensearch/opensearch.go
> +	if req.Path == "" && esUrlString[len(esUrlString)-1:] != "/" {
```suggestion
	if req.Path == "" && osUrlString[len(osUrlString)-1:] != "/" {
```

2024-09-17 10:53 UTC, njvrzm commented on pkg/opensearch/opensearch.go
> +	return esUrlString, nil
```suggestion
	return osUrlString, nil
```

2024-09-17 10:53 UTC, njvrzm commented on pkg/opensearch/opensearch.go
> +	request, err := http.NewRequestWithContext(ctx, req.Method, esUrl, bytes.NewBuffer(req.Body))
```suggestion
	request, err := http.NewRequestWithContext(ctx, req.Method, osUrl, bytes.NewBuffer(req.Body))
```

2024-09-17 10:53 UTC, njvrzm commented on pkg/opensearch/opensearch.go
> +	esUrl, err := createOpensearchURL(req, req.PluginContext.DataSourceInstanceSettings.URL)
```suggestion
	osUrl, err := createOpensearchURL(req, req.PluginContext.DataSourceInstanceSettings.URL)
```

2024-09-17 10:53 UTC, njvrzm commented on pkg/opensearch/opensearch.go
> +	}
```suggestion
	if encoding := response.Header.Get("Content-Encoding"); encoding != "" {
		responseHeaders["content-encoding"] = []string{encoding}
	}
```

2024-09-17 13:31 UTC, njvrzm commented
Just to follow on from the above, there's a different error if you point to a valid http endpoint that's not opensearch. Maybe should use the same generic error here too.

<img width="1182" alt="Screenshot 2024-09-17 at 15 30 07" src="https://github.com/user-attachments/assets/bbb8c221-f9ad-4e27-b206-65c607d5e4ad">

2024-09-20 21:31 UTC, iwysiu commented
@njvrzm sorry for the messy history- i accidentally amended onto the last commit instead of making a new one. I made the renaming changes and added the `Failed to connect to server` error. Can you send me the valid endpoint you're using that doesn't return the correct data? I think we originally weren't handling that properly but i can add an error for it

2024-09-23 11:27 UTC, njvrzm commented
Ah, sorry, when I said "valid endpoint" I just meant like if you point it to http://www.yahoo.com or the like. A valid HTTP endpoint that isn't an opensearch server.

2024-09-23 13:26 UTC, njvrzm approved these changes
Looks good! Thanks for the updates. If you want to repress the json error when visiting a non-opensearch http endpoint feel free, but I don't think it's that important :)

2024-09-23 15:40 UTC, iwysiu commented
double checked, it looks like the json error is already being supressed, so i think we're good!

2024-09-23 15:40 UTC, merged